logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      database: test
      auto-index-creation: true
  liquibase:
    change-log: classpath:root-changelog.xml
mongock:
  change-logs-scan-package: com.example.demo.config
test:
  map:
    QWE: 111
    ASD: 222
    ZXC: 333